### ISSUE TITLE
java-exe-exited-with-code-2

### ISSUE THREAD

**Issue by kntiwary** [Microsoft/mobile-center-sdk-dotnet#309]
It did not sovlve my problem @guperrot Please have a look at https://forums.xamarin.com/discussion/84125/how-to-fix-java-exe-exited-with-code-2

**Comment by guperrot** [comment]
@kntiwary are you sure you enabled multi-dex ? What build config are you using and what are your build options?

**Comment by MisterJimson** [comment]
Why does this library add so many methods? I have made multiple Xamarin apps with many dependencies and never have needed to enable mutidex on any of them. Creating a small app and adding Mobile Center forces me to.

(by the way enabling multidex did solve this issue for me)

**Comment by guperrot** [comment]
Hi @MisterJimson it's not Mobile Center directly but the Xamarin Firebase package and its support lib and google play dependencies.

A bug has been opened against Xamarin as this issue does not exist with Android Studio Java projects: https://bugzilla.xamarin.com/show_bug.cgi?id=55117

**Comment by MisterJimson** [comment]
I see. Thanks for the link. That bug is annoying. 

I've been sticking to 23.x support packages for a while, which is probably why I didn't run into this.
