### ISSUE TITLE
Mobile Center Push Incompatible with Xamarin.Forms AppLinks

### ISSUE THREAD

**Issue by brminnick** [Microsoft/mobile-center-sdk-dotnet#374]
### Description
If a File -> New Blank Xamarin.Forms app is created, the Xamarin.Forms App Links NuGet Package is added and the Mobile Center Push NuGet Package is added, the Android app will crash at run-time.

This runtime crash is happening because Xamarin.Forms App Links has a dependency on Xamarin.GooglePlayServices.Basement v29.0.0.1, but Mobile Center Push has a dependency on Xamarin.GooglePlayServices.Basement v42.1021.1.

### Reproduction
https://github.com/brminnick/XamarinForms-MobileCenterPush-AppLinks-Repro/

### Bug Tracking
This bug is being tracked by the Xamarin.Forms team [in Bugzilla](https://bugzilla.xamarin.com/show_bug.cgi?id=54383).

### Runtime Crash
>Could not load type of field 'Xamarin.Forms.Platform.Android.AppLinks.AndroidAppLinks:_client' (0) due to: Could not resolve type with token 01000013 (from typeref, class/assembly Android.Gms.Common.Apis.GoogleApiClient, Xamarin.GooglePlayServices.Basement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Xamarin.GooglePlayServices.Basement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:Android.Gms.Common.Apis.GoogleApiClient member:<none>

**Comment by guperrot** [comment]
Hi, since Mobile Center SDK is compatible with the latest version of those packages, the bug should be on Xamarin side to fix as they are not compatible with latest packages and they should.

Mobile Center should not downgrade as people would have issue with updating those dependent packages.

**Comment by guperrot** [comment]
Bug will be fixed by App Links, not Mobile Center.
Reminder: https://github.com/Microsoft/mobile-center-sdk-ios/issues/601
