### ISSUE TITLE
Updated from 0.13.1 to 0.14 and Receiving "error: cannot find symbol" on Android Build

### ISSUE THREAD

**Issue by renzska** [Microsoft/mobile-center-sdk-dotnet#385]
I updated from 0.13.1 to 0.14 and am now receiving "error: cannot find symbol" when building for Android. 

Minimum Android Version: API Level 15 (4.0.3)
Target: API 25

```
/DroidApp/obj/Debug/android/src/md5bf7db09e0a40f5ef5da2cf34b1b37d54/PlatformCrashes_CrashListener.java(45,45): Error:  error: cannot find symbol
		com.microsoft.azure.mobile.crashes.Crashes.WrapperSdkListener
  symbol:   class WrapperSdkListener
  location: class Crashes
 (SafeUT.Droid) javac

/DroidApp/obj/Debug/android/src/md5bf7db09e0a40f5ef5da2cf34b1b37d54/PlatformCrashes_GetLastSessionCrashReportCallback.java(29,29): Error:  error: cannot find symbol
		com.microsoft.azure.mobile.ResultCallback
  symbol:   class ResultCallback
  location: package com.microsoft.azure.mobile
 (SafeUT.Droid) javac

/DroidApp/obj/Debug/android/src/mono/com/microsoft/azure/mobile/crashes/Crashes_WrapperSdkListenerImplementor.java(45,45): Error:  error: cannot find symbol
		com.microsoft.azure.mobile.crashes.Crashes.WrapperSdkListener
  symbol:   class WrapperSdkListener
  location: class Crashes
 (SafeUT.Droid)
```
Thanks,

John

**Comment by ctarmor** [comment]
I am having the same problem.

**Comment by guperrot** [comment]
Hi @renzska @ctarmor sorry for the late reply, I have not received notifications.
I can't reproduce your problem, have you tried clean build?
Any source code you can share or can you reproduce it in a sample app?

**Comment by guperrot** [comment]
Actually the symbols you are referring to are not in 0.14.0 anymore indeed, this is most likely a clean build issue.

**Comment by guperrot** [comment]
No news here so we assume clean build was the solution.

**Comment by renzska** [comment]
Sorry about the delay. A clean build did not resolve the issue. On a full restart of my Mac was necessary. I’ve seen this with other packages like Fody. For some reason msbuild holds onto something which is not cleared by a clean, rebuild, or even restart of VS for Mac. The only solution is a restart of the computer.

**Comment by guperrot** [comment]
Ok, glad you could figure out a way to "clean" your work environment.
Thanks for using Mobile Center.
