### ISSUE TITLE
Upgrade to 4.0.1 icompatible with Xamarin PCL ?

### ISSUE THREAD

**Issue by ctarmor** [Microsoft/mobile-center-sdk-dotnet#386]
I have been working with Xamarin PCL, suddenly v4.0.1 is incompatible with my UWP and my Xamarin PCL..  It IS compatible with my Android project. 

What should I do ??

Error:
You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259'

**Comment by dhei** [comment]
Hi @ctarmor 

Mobile Center **Tables** and **Identities** (preview) feature takes a dependency on Azure Mobile Apps .NET SDK, and Azure Mobile Apps .NET SDK made a breaking change in v4.0.0 by moving to .NET standard 1.4. Unfortunately Xamarin.Forms using PCL is no longer supported in v4.0.0 and Xamarin.Forms using .NET standard is the way to go. Essentially your Xamarin.Forms project should work if you're migrate to .NET standard. If you cannot migrate and want to stick with PCL, then you probably need to do add the following code to project.json to your PCL project to make it work. BTW, you can find a working sample from [here](https://github.com/dhei/azure-mobile-apps-xamarinforms-login-sample/blob/master/dihei_empty_node/project.json#L7-L10).

```
"frameworks": {      
  "netstandard1.4": {        
    "imports": "portable-win8+net45+wpa81"      
  }
} 
```

**Comment by guperrot** [comment]
Closing as this issue was reported to the wrong SDK.
