### ISSUE TITLE
Azure Mobile Center build resulting in error XA5213: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by balazsbonis** [Microsoft/mobile-center-sdk-dotnet#395]
I have a Xamarin forms solution targeting Android, iOS and UWP that I am building using the [Azure Mobile Center](https://mobile.azure.com/). I added the latest (0.14.0) packages of `Microsoft.Azure.Mobile`, `Microsoft.Azure.Mobile.Analytics` and `Microsoft.Azure.Mobile.Crashes` to the platform-specific libraries as well as the common shared Xamarin.Forms project, and I added the following line of code into the init section for the Xamarin Forms App.xaml.cs file:
```
MobileCenter.Start("uwp={{mySecret}};" +
                   "android={{mySecret}};" +
                   "ios={{mySecret}};",
    typeof(Analytics));
```
Locally, I can build all projects fine, and I can run the projects as well. However, if I try to build it on AMC, I get the following error:
```
"d:\a\1\s\src\MyApp.UI.Android\MyApp.UI.Android.csproj" (default target) (6:2) ->
  COMPILETODALVIK : UNEXPECTED TOP-LEVEL error :  [d:\a\1\s\src\MyApp.UI.Android\MyApp.UI.Android.csproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1965,3): error XA5213: java.lang.OutOfMemoryError. Consider increasing the value of $(JavaMaximumHeapSize). Java ran out of memory while executing 'java.exe -jar "C:\Program Files (x86)\Android\android-sdk\build-tools\25.0.2\\lib\dx.jar" --no-strict --dex --output=obj\Release\android\bin obj\Release\android\bin\classes "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v7.1\mono.android.jar" 
```
I tried to degrade to the previous version (0.13.0), but it results in the same error message. Then just for an experiment, I removed the packages from the solution (all 3) along with that line of code, and it built fine, so I'm certain that the issue is caused by one of them. Have I missed a step while setting this up, or is there a bug in the package somewhere?

Thank you!

**Comment by guperrot** [comment]
Hi, it's the build system having too much to handle, it does not happen for anyone else or at least this is the first report of this kind for Mobile Center.

As the message suggests: 
>  Consider increasing the value of $(JavaMaximumHeapSize)

You can do this by editing the csproj:

```
<PropertyGroup>
    <JavaMaximumHeapSize>1G</JavaMaximumHeapSize>
</PropertyGroup>
```

You may have to clean build or sometimes restart the IDE for this to take effect.
You might also have to try different values for your build.

**Comment by balazsbonis** [comment]
Hi @guperrot,

That actually fixes the build, however I still find it strange I have to specify this value manually. Can this be added as a default into the Android csproj files?

**Comment by guperrot** [comment]
@balazsbonis this is not something our SDK controls, it's related to the IDE. Only some apps will need this.
