### ISSUE TITLE
Using MobileCenter.Start() in OnLaunched() causes errors in logs UWP SDK

### ISSUE THREAD

**Issue by snrnats** [Microsoft/mobile-center-sdk-dotnet#396]
In MobileCenter UWP documentation you suggest adding `MobileCenter.Start()` in the application `OnLaunched()` method. But it will produce an error to log if you try to start an application while it's already running or suspended. E.g. clicking the app tile or starting from application list when the app is running.
`[MobileCenter] ERROR: Failed to start services
Microsoft.Azure.Mobile.MobileCenterException: Multiple attempts to configure Mobile Center
   at Microsoft.Azure.Mobile.MobileCenter.InstanceConfigure(String appSecretOrSecrets)
   at Microsoft.Azure.Mobile.MobileCenter.StartInstanceAndConfigure(String appSecret, Type[] services)`

**Comment by achocron** [comment]
This is actually harmless; thanks for pointing it out. We definitely need to show a better log in this case.
