### ISSUE TITLE
Can't see data in Mobile Center

### ISSUE THREAD

**Issue by Oleksandr-Tokmakov** [Microsoft/mobile-center-sdk-dotnet#445]
I can't see any data in mobile center - neither crashes nor analytics from android os. It's just empty and says - waiting for data. I use version 0.15.0 - latest stable at this moment.

In output window I found following:
> 09-24 21:07:00.468 F/MobileCenter(22564): Mobile Center SDK configured successfully.
> 09-24 21:07:00.481 W/MobileCenter(22564): Unable to get installID from Shared Preferences

**Comment by guperrot** [comment]
Hi the log you see is normal the first time as we generate the installId first before using it.
To investigate you need to increase the log level to verbose by calling `MobileCenter.LogLevel = LogLevel.Verbose` before `MobileCenter.Start` and then please attach the full session logs (all logs having tag starting with MobileCenter, sometimes they have the module suffix).

**Comment by Oleksandr-Tokmakov** [comment]
Hey, thanks for the answer. On next day test crashes appeared in mobile center. So it works.
Sorry for disturbing you, however I wonder how could it be. I tried to fix it for an hour and I sent ~10 crash reports and they just appeared on next day.

**Comment by guperrot** [comment]
Hi, that is probably a server related issue.
Verbose logs can be used to look at http request logs and check the crash is sent by SDK and have 200 status code.
If you get a 200 in logs but nothing in portal, you need to create a support ticket via the portal button as server side support is not tracked on github (only SDKs are).

**Comment by guperrot** [comment]
No answer.
