### ISSUE TITLE
Add handler for exceptions on AppDomain for Xamarin Android SDK

### ISSUE THREAD

**Issue by wcoder** [Microsoft/mobile-center-sdk-dotnet#468]
May be is good thought for add handler for `AppDomain.CurrentDomain.UnhandledException` exceptions?

How is this done in Hockey App SDK:
https://github.com/bitstadium/HockeySDK-Xamarin/blob/master/source/HockeySDK.AndroidBindings/Additions/CrashManager.cs#L62

**Comment by guperrot** [comment]
Hi, no this one is redundant on Android with the handler we use. We use it on iOS though.
Plus it does not enable reading the exception to structure into non raw json in Android.
