### ISSUE TITLE
InvalidOperationException in SessionTracker..ctor UWP SDK

### ISSUE THREAD

**Issue by snrnats** [Microsoft/mobile-center-sdk-dotnet#484]
I am getting a lot of new crash reports for my UWP app. More details in an attached stack trace and a dump file. I am using 0.16.0 SDK
[stackTrace.txt](https://github.com/Microsoft/mobile-center-sdk-dotnet/files/1432424/stackTrace.txt)
[83098ccc-8f90-45b5-9da6-d7aa4fca1149.ext.zip](https://github.com/Microsoft/mobile-center-sdk-dotnet/files/1432426/83098ccc-8f90-45b5-9da6-d7aa4fca1149.ext.zip)

`
STOWED_EXCEPTION_System.InvalidOperationException_80131509_CryptoCoins.UWP.dll!System::Collections::Generic::Dictionary$2_System::Int64,System::Guid_::ValueCollection::Enumerator.MoveNext
`

`
System::Collections::Generic::Dictionary$2_System::Int64,System::Guid_::ValueCollection::Enumerator.MoveNext	0xA4	
System::Linq::Enumerable.Aggregate_System.Guid,_System.__Canon_	0x7E	
Microsoft::Azure::Mobile::Analytics::Channel::SessionTracker..ctor	0x1D9	
Microsoft::Azure::Mobile::Analytics::Analytics.CreateSessionTracker	0x4D	
Microsoft::Azure::Mobile::Analytics::Analytics.ApplyEnabledState	0x61	
Microsoft::Azure::Mobile::Analytics::Analytics.OnChannelGroupReady	0x4C	
Microsoft::Azure::Mobile::MobileCenter.StartService	0xF2	
Microsoft::Azure::Mobile::MobileCenter.StartInstance	0x1A5	
Microsoft::Azure::Mobile::MobileCenter.StartInstanceAndConfigure	0x29	
Microsoft::Azure::Mobile::MobileCenter.PlatformStart	0x54	
CryptoCoins::UWP::App.ConfigureMobileCenter	0xC2	
CryptoCoins::UWP::App..ctor	0x90	
CryptoCoins::UWP::Program::__c._Main_b__0_0	0x18	
SQLitePCL::SQLite3Provider_e_sqlite3::NativeMethods::callback_rollback.Invoke	0x28	
__Interop::ReverseComStubs.Stub_20_System.__Canon_	0x6D	
`

**Comment by achocron** [comment]
Investigating this now. Do you happen to know a way to repro?

**Comment by guperrot** [comment]
As we are investigating other changes for the next stable release, you can have the fix now but it will be only a prelease.

If you can't wait for next official release, please try out prerelease version `0.17.1-r0005-68a3a97`.

**Comment by snrnats** [comment]
Thank you for the update! For now I am using an older version with placement of the initialization code in OnLaunched. I prefer to wait for the next official release.

**Comment by guperrot** [comment]
[0.17.1](https://github.com/Microsoft/mobile-center-sdk-dotnet/releases/tag/0.17.1) is released and contains the fix as well.
