### ISSUE TITLE
Crashes.GetErrorAttachments is not called in Xamarin.iOS

### ISSUE THREAD

**Issue by alexsorokoletov** [Microsoft/mobile-center-sdk-dotnet#495]
I used Contoso.iOS.Puppet app and changed FinishLaunching to add additional information to the crash.

However, generating test crash does trigger GetErrorAttachments after crash or on a next app start (like Android dos).

Please advise.

```
        public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
        {
            // Override point for customization after application launch.
            // If not required for your application you can safely delete this method

            MobileCenter.LogLevel = LogLevel.Verbose;
            MobileCenter.SetLogUrl("https://in-integration.dev.avalanch.es");
            MobileCenter.Start("MY_APP_ID_HERE", typeof(Analytics), typeof(Crashes));
            try
            {
                ThrowAnException();
            }
            catch (Exception e)
            {
                MobileCenterLog.Verbose("THETAG", "THEMESSAGE", e);
            }
            //----------
            Crashes.GetErrorAttachments = OnGenerateErrorAttach;
            Crashes.ShouldProcessErrorReport = (ErrorReport report) =>
                       {
                           return true;
                       };
            //----------
            Analytics.SetEnabledAsync(true);
            System.Diagnostics.Debug.WriteLine("ANALYTICS: " + Analytics.IsEnabledAsync().Result);
            return true;
        }

        private IEnumerable<ErrorAttachmentLog> OnGenerateErrorAttach(ErrorReport report)
        {
            yield return ErrorAttachmentLog.AttachmentWithText("abc", "def.txt");
        }
```

Original source code: https://github.com/Microsoft/mobile-center-sdk-dotnet/blob/880fac6b1ea87e51ab0dbbe0da8a1efb4b1a59e3/Apps/Contoso.iOS.Puppet/AppDelegate.cs

Please advise as I would like to provide additional information with the crash.

**Comment by guperrot** [comment]
Hi, you need to set up the callback before `MobileCenter.Start` as crashes are processed as soon as you call Start.

**Comment by alexsorokoletov** [comment]
@guperrot thanks, let me try right away.

**Comment by alexsorokoletov** [comment]
Thank you, @guperrot. According to application output, now the method is being called and I see my filename in the logs (below).

`  "file_name" : "def.txt",`


```
2017-11-07 23:30:58.547 Contoso.iOS.Puppet[4244:27193174] [MobileCenter] DEBUG: -[MSChannelDefault flushQueue]_block_invoke/151 Sending 1/1 log(s), group Id: Crashes, batch Id:DDB88BE3-55FB-4363-AB34-0FEF74FEC794, payload:
{
  "device" : {
    "oem_name" : "Apple",
    "wrapper_sdk_version" : "0.17.1",
    "wrapper_runtime_version" : "11.2.0",
    "os_name" : "iOS",
    "app_version" : "0.17.2",
    "time_zone_offset" : -300,
    "sdk_version" : "0.14.1",
    "screen_size" : "1334x750",
    "locale" : "en_US",
    "os_build" : "16G29",
    "app_namespace" : "com.microsoft.azure.mobile.xamarin.puppet",
    "wrapper_sdk_name" : "mobilecenter.xamarin",
    "os_version" : "11.1",
    "sdk_name" : "mobilecenter.ios",
    "model" : "x86_64",
    "app_build" : "0.17.2"
  },
  "id" : "2C1DD8C4-5119-4F91-8E28-0A7C7346C8C0",
  "data" : "YWJj",
  "file_name" : "def.txt",
  "sid" : "DD06AF2F-A495-4FC6-A887-D021948362D0",
  "type" : "error_attachment",
  "timestamp" : "2017-11-08T04:30:58.498Z",
  "error_id" : "749F5775-07B5-421D-B72C-2E05B6A1DB3A",
  "content_type" : "text/plain"
}
```

Unfortunately, this crash does not make to the Mobile Center. 
Should I open a new issue for that or is there an FAQ for issues like that?

**Comment by guperrot** [comment]
Do you see the http response codes for both the crash sent and the attachment sent?

**Comment by guperrot** [comment]
Also it seems you forked our repo dev app, did you get rid of all the `MobileCenter.SetLogUrl` statements? Otherwise it does not target prod.

**Comment by alexsorokoletov** [comment]
I did remove the url and copied app secret again and everything started working.
Thank you, @guperrot. 

Is that true that without dSYM uploaded no crashes will be visible in the iOS app in Mobile Center? (https://docs.microsoft.com/en-us/mobile-center/crashes/ios)
Wondering how test crash under debug configuration is different cause it shows up.

**Comment by guperrot** [comment]
Hi, dSYM are required only if the crash occurs in objective C / swift bound code.
For your pure .NET stack traces you don't need symbols.

**Comment by alexsorokoletov** [comment]
Great, thank you. Please close the issue

**Comment by Steven-Mark-Ford** [comment]
@guperrot 

> Hi, you need to set up the callback before MobileCenter.Start as crashes are processed as soon as you call Start.

This is no where in the app center wiki. Could someone add this before closing off this issue.

**Comment by AdamDiament** [comment]
> @guperrot
> 
> > Hi, you need to set up the callback before MobileCenter.Start as crashes are processed as soon as you call Start.
> 
> This is no where in the app center wiki. Could someone add this before closing off this issue.
> 
> BTW: I get the same issue on portable class library.

@Steven-Mark-Ford sorry for piggy backing on an old issue - but  if the callback is processed as soon as you call start, how can you include an attachment that is up to date at the time the actual crash happens? I was hoping the callback would be executed right before the crash is reported.
